#!/bin/bash

cd $( dirname $0 )

VERSION=$( cat debian/changelog | head -n 1 | sed -e "s/^[^(]*(//" -e "s/).*//" )
REVISION=1

VERSION_FILE=".rpm-version"
if [[ -n "$1" ]] ; then
    VERSION_FILE="${VERSION_FILE}-$1"
fi

OLD_VERSION_FULL=
OLD_VERSION=
OLD_REVISION=
if [[ -f "${VERSION_FILE}" ]] ; then
    OLD_VERSION_FULL=$( cat "${VERSION_FILE}" | grep -P -v '^\s*(#.*|$)' | head -n 1 | sed -e 's/[ 	].*//' )
fi

if [[ -n "${OLD_VERSION_FULL}" ]] ; then

    OLD_VERSION=$( echo "${OLD_VERSION_FULL}" | sed -e 's/-.*//' )
    OLD_REVISION=$( echo "${OLD_VERSION_FULL}" | sed -e 's/^[^-]*-//' )

    if [[ -z "${OLD_VERSION}" ]] ; then
        OLD_VERSION="${DEBIAN_VERSION}"
    fi

    if [[ -z "${OLD_REVISION}" ]] ; then
        OLD_REVISION="0"
    fi

    if [[ "${OLD_VERSION}" != "${VERSION}" ]] ; then
        REVISION=1
    else
        REVISION=$(( ${OLD_REVISION} + 1 ))
    fi

fi

echo "${REVISION}"

# vim: ts=4 et
