---

runs:
  using: "composite"
  steps:
    - name: Install PIP modules
      id: install-pip-modules
      shell: bash
      run: |
        pip install --upgrade --upgrade-strategy eager pytest
        pip list --format columns
    - name: Executing PyTest
      id: pytest
      shell: bash
      run: pytest --verbose

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
